/* THIS FILE IS AUTOMATICALLY GENERATED */
/* zeofuncGenerator.py 2007-03-31 19:13:44.312000 */

void calc_HF_ClipMap (ZMAP hMap, float ClipAlt, float SetAlt, int ClipMode, bool ShowProgress)
{
    static CzFunc localClipMap;
    
    if (localClipMap.GetZVAR() == NULL)
        localClipMap.GetFunc("calc.HF.ClipMap");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localClipMap.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ClampMap (ZMAP hMap, float MinAlt, float MaxAlt, bool ShowProgress)
{
    static CzFunc localClampMap;
    
    if (localClampMap.GetZVAR() == NULL)
        localClampMap.GetFunc("calc.HF.ClampMap");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localClampMap.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ScaleMap (ZMAP hMap, float val, bool ShowProgress)
{
    static CzFunc localScaleMap;
    
    if (localScaleMap.GetZVAR() == NULL)
        localScaleMap.GetFunc("calc.HF.ScaleMap");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localScaleMap.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ShiftMap (ZMAP hMap, float val, bool ShowProgress)
{
    static CzFunc localShiftMap;
    
    if (localShiftMap.GetZVAR() == NULL)
        localShiftMap.GetFunc("calc.HF.ShiftMap");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localShiftMap.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_GradFilter (ZMAP hMap, int nLevels, float Threshold, bool ShowProgress, LPVOID pMaskMap)
{
    static CzFunc localGradFilter;
    
    if (localGradFilter.GetZVAR() == NULL)
        localGradFilter.GetFunc("calc.HF.GradFilter");

    CzList args;
    
    CzVar varpMaskMap (args.CreateItem(VarID_void, "pMaskMap"));
    varpMaskMap.SetValue(VarID_void, & pMaskMap);

    CzVar retVar(localGradFilter.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_CurvFilter (ZMAP hMap, int nLevels, float Threshold, bool ShowProgress, LPVOID pMaskMap)
{
    static CzFunc localCurvFilter;
    
    if (localCurvFilter.GetZVAR() == NULL)
        localCurvFilter.GetFunc("calc.HF.CurvFilter");

    CzList args;
    
    CzVar varpMaskMap (args.CreateItem(VarID_void, "pMaskMap"));
    varpMaskMap.SetValue(VarID_void, & pMaskMap);

    CzVar retVar(localCurvFilter.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_CombineMaps (ZMAP hMap1, ZMAP hMap2, int MixMode, int offset_xmid, int offset_ymid)
{
    static CzFunc localCombineMaps;
    
    if (localCombineMaps.GetZVAR() == NULL)
        localCombineMaps.GetFunc("calc.HF.CombineMaps");

    CzList args;
    
    CzVar varoffset_ymid (args.CreateItem(VarID_int, "offset_ymid"));
    varoffset_ymid.SetValue(VarID_int, & offset_ymid);

    CzVar retVar(localCombineMaps.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ErodeChannel (ZMAP hMap, int MaxCycles, int MinLength, int MaxLength, float DeltaHF, float MemDecay, bool BlurDir, bool ShowProgress)
{
    static CzFunc localErodeChannel;
    
    if (localErodeChannel.GetZVAR() == NULL)
        localErodeChannel.GetFunc("calc.HF.ErodeChannel");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localErodeChannel.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ErodeChannelEx (ZMAP hMap, ZMAP hMaskMap, int MinLength, int MaxLength, float DeltaHF, float MemDecay, bool BlurDir, bool ShowProgress)
{
    static CzFunc localErodeChannelEx;
    
    if (localErodeChannelEx.GetZVAR() == NULL)
        localErodeChannelEx.GetFunc("calc.HF.ErodeChannelEx");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localErodeChannelEx.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ErodeThermal (ZMAP hMap, int MaxCycles, int MaxLength, float LossFraction, float GradThreshold, bool ShowProgress)
{
    static CzFunc localErodeThermal;
    
    if (localErodeThermal.GetZVAR() == NULL)
        localErodeThermal.GetFunc("calc.HF.ErodeThermal");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localErodeThermal.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_ErodeThermalEx (ZMAP hMap, ZMAP hMaskMap, int MaxLength, float LossFraction, float GradThreshold, bool ShowProgress)
{
    static CzFunc localErodeThermalEx;
    
    if (localErodeThermalEx.GetZVAR() == NULL)
        localErodeThermalEx.GetFunc("calc.HF.ErodeThermalEx");

    CzList args;
    
    CzVar varShowProgress (args.CreateItem(VarID_bool, "ShowProgress"));
    varShowProgress.SetValue(VarID_bool, & ShowProgress);

    CzVar retVar(localErodeThermalEx.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_Inflate (ZMAP hHF, ZMAP hDM, int levels)
{
    static CzFunc localInflate;
    
    if (localInflate.GetZVAR() == NULL)
        localInflate.GetFunc("calc.HF.Inflate");

    CzList args;
    
    CzVar varlevels (args.CreateItem(VarID_int, "levels"));
    varlevels.SetValue(VarID_int, & levels);

    CzVar retVar(localInflate.Execute((ZLIST)args.GetZVAR()));
    return;
}

void calc_HF_InflateMosaic (ZMAP hMapSrc, ZMAP hMapDest, const char * FileName, const char * MapName, int TileSize, ZFORMAT hFormat, ZMAP hDM, int levels)
{
    static CzFunc localInflateMosaic;
    
    if (localInflateMosaic.GetZVAR() == NULL)
        localInflateMosaic.GetFunc("calc.HF.InflateMosaic");

    CzList args;
    
    CzVar varlevels (args.CreateItem(VarID_int, "levels"));
    varlevels.SetValue(VarID_int, & levels);

    CzVar retVar(localInflateMosaic.Execute((ZLIST)args.GetZVAR()));
    return;
}

bool calc_HF_GenPeakOverlay (ZMAP hMap, int Radius, float Height, int ShapeMode)
{
    static CzFunc localGenPeakOverlay;
    
    if (localGenPeakOverlay.GetZVAR() == NULL)
        localGenPeakOverlay.GetFunc("calc.HF.GenPeakOverlay");

    CzList args;
    
    CzVar varShapeMode (args.CreateItem(VarID_int, "ShapeMode"));
    varShapeMode.SetValue(VarID_int, & ShapeMode);

    CzVar retVar(localGenPeakOverlay.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

ZLIST calc_AM_GetFilterList ()
{
    static CzFunc localGetFilterList;
    
    if (localGetFilterList.GetZVAR() == NULL)
        localGetFilterList.GetFunc("calc.AM.GetFilterList");

    CzVar retVar(localGetFilterList.Execute());
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}
short calc_AM_FilterPixel (short InputCode, ZVAR Buf, ZLIST Filter)
{
    static CzFunc localFilterPixel;
    
    if (localFilterPixel.GetZVAR() == NULL)
        localFilterPixel.GetFunc("calc.AM.FilterPixel");

    CzList args;
    
    CzVar varFilter (args.CreateItem(VarID_varlist, "Filter"));
    varFilter.SetValue(VarID_varlist, & Filter);

    CzVar retVar(localFilterPixel.Execute((ZLIST)args.GetZVAR()));
    
    short retValue;
    retVar.GetValue(VarID_short, &retValue);
    return retValue;

}

ZVAR calc_AM_GetClimateByCode (short InputCode)
{
    static CzFunc localGetClimateByCode;
    
    if (localGetClimateByCode.GetZVAR() == NULL)
        localGetClimateByCode.GetFunc("calc.AM.GetClimateByCode");

    CzList args;
    
    CzVar varInputCode (args.CreateItem(VarID_short, "InputCode"));
    varInputCode.SetValue(VarID_short, & InputCode);

    CzVar retVar(localGetClimateByCode.Execute((ZLIST)args.GetZVAR()));
    
    ZVAR retValue;
    retVar.GetValue(VarID_Climate, &retValue);
    return retValue;

}

ZVAR calc_AM_GetLandTypeByCode (short InputCode)
{
    static CzFunc localGetLandTypeByCode;
    
    if (localGetLandTypeByCode.GetZVAR() == NULL)
        localGetLandTypeByCode.GetFunc("calc.AM.GetLandTypeByCode");

    CzList args;
    
    CzVar varInputCode (args.CreateItem(VarID_short, "InputCode"));
    varInputCode.SetValue(VarID_short, & InputCode);

    CzVar retVar(localGetLandTypeByCode.Execute((ZLIST)args.GetZVAR()));
    
    ZVAR retValue;
    retVar.GetValue(VarID_LandType, &retValue);
    return retValue;

}

ZVAR calc_AM_GetPixelColour (short InputCode)
{
    static CzFunc localGetPixelColour;
    
    if (localGetPixelColour.GetZVAR() == NULL)
        localGetPixelColour.GetFunc("calc.AM.GetPixelColour");

    CzList args;
    
    CzVar varInputCode (args.CreateItem(VarID_short, "InputCode"));
    varInputCode.SetValue(VarID_short, & InputCode);

    CzVar retVar(localGetPixelColour.Execute((ZLIST)args.GetZVAR()));
    
    ZVAR retValue;
    retVar.GetValue(VarID_colour, &retValue);
    return retValue;

}

short calc_AM_GetIDfromColour (ZVAR InputColour)
{
    static CzFunc localGetIDfromColour;
    
    if (localGetIDfromColour.GetZVAR() == NULL)
        localGetIDfromColour.GetFunc("calc.AM.GetIDfromColour");

    CzList args;
    
    CzVar varInputColour (args.CreateItem(VarID_colour, "InputColour"));
    varInputColour.SetValue(VarID_colour, & InputColour);

    CzVar retVar(localGetIDfromColour.Execute((ZLIST)args.GetZVAR()));
    
    short retValue;
    retVar.GetValue(VarID_short, &retValue);
    return retValue;

}

void calc_AM_GenMap ()
{
    static CzFunc localGenMap;
    
    if (localGenMap.GetZVAR() == NULL)
        localGenMap.GetFunc("calc.AM.GenMap");

    CzVar retVar(localGenMap.Execute());
    return;
}
void calc_TN_GenMap ()
{
    static CzFunc localGenMap;
    
    if (localGenMap.GetZVAR() == NULL)
        localGenMap.GetFunc("calc.TN.GenMap");

    CzVar retVar(localGenMap.Execute());
    return;
}
bool calc_TN_GenArea (int TileStateFlag, ZLIST maps, ZLIST area, ZLIST params, ZLIST prog)
{
    static CzFunc localGenArea;
    
    if (localGenArea.GetZVAR() == NULL)
        localGenArea.GetFunc("calc.TN.GenArea");

    CzList args;
    
    CzVar varprog (args.CreateItem(VarID_varlist, "prog"));
    varprog.SetValue(VarID_varlist, & prog);

    CzVar retVar(localGenArea.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

void calc_LM_GenMap ()
{
    static CzFunc localGenMap;
    
    if (localGenMap.GetZVAR() == NULL)
        localGenMap.GetFunc("calc.LM.GenMap");

    CzVar retVar(localGenMap.Execute());
    return;
}
void calc_TX_GenMap ()
{
    static CzFunc localGenMap;
    
    if (localGenMap.GetZVAR() == NULL)
        localGenMap.GetFunc("calc.TX.GenMap");

    CzVar retVar(localGenMap.Execute());
    return;
}
bool calc_TX_GenMapPro_CalcArea (int TileStateFlag, ZLIST maps, ZLIST area, ZLIST params, ZLIST prog)
{
    static CzFunc localCalcArea;
    
    if (localCalcArea.GetZVAR() == NULL)
        localCalcArea.GetFunc("calc.TX.GenMapPro.CalcArea");

    CzList args;
    
    CzVar varprog (args.CreateItem(VarID_varlist, "prog"));
    varprog.SetValue(VarID_varlist, & prog);

    CzVar retVar(localCalcArea.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

ZLIST calc_alpha_ExportExpress (const char * FileName, ZMAP hMap, ZLIST hFilter, ZFORMAT hFormat, int LayersPerImage, bool MosaicFlag, int TileSize, bool ShowReport)
{
    static CzFunc localExportExpress;
    
    if (localExportExpress.GetZVAR() == NULL)
        localExportExpress.GetFunc("calc.alpha.ExportExpress");

    CzList args;
    
    CzVar varShowReport (args.CreateItem(VarID_bool, "ShowReport"));
    varShowReport.SetValue(VarID_bool, & ShowReport);

    CzVar retVar(localExportExpress.Execute((ZLIST)args.GetZVAR()));
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}

const char * classes_landtype_GetBaseTextureNameByID (short InputCode)
{
    static CzFunc localGetBaseTextureNameByID;
    
    if (localGetBaseTextureNameByID.GetZVAR() == NULL)
        localGetBaseTextureNameByID.GetFunc("classes.landtype.GetBaseTextureNameByID");

    CzList args;
    
    CzVar varInputCode (args.CreateItem(VarID_short, "InputCode"));
    varInputCode.SetValue(VarID_short, & InputCode);

    CzVar retVar(localGetBaseTextureNameByID.Execute((ZLIST)args.GetZVAR()));
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}

const char * classes_landtype_GetTypeNameByID (short InputCode)
{
    static CzFunc localGetTypeNameByID;
    
    if (localGetTypeNameByID.GetZVAR() == NULL)
        localGetTypeNameByID.GetFunc("classes.landtype.GetTypeNameByID");

    CzList args;
    
    CzVar varInputCode (args.CreateItem(VarID_short, "InputCode"));
    varInputCode.SetValue(VarID_short, & InputCode);

    CzVar retVar(localGetTypeNameByID.Execute((ZLIST)args.GetZVAR()));
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}

const char * classes_landtype_GetName (ZVAR hLandType)
{
    static CzFunc localGetName;
    
    if (localGetName.GetZVAR() == NULL)
        localGetName.GetFunc("classes.landtype.GetName");

    CzList args;
    
    CzVar varhLandType (args.CreateItem(VarID_LandType, "hLandType"));
    varhLandType.SetValue(VarID_LandType, & hLandType);

    CzVar retVar(localGetName.Execute((ZLIST)args.GetZVAR()));
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}

ZFORMAT classes_format_GetActiveFormat (const char * MapName, int MapTypeID)
{
    static CzFunc localGetActiveFormat;
    
    if (localGetActiveFormat.GetZVAR() == NULL)
        localGetActiveFormat.GetFunc("classes.format.GetActiveFormat");

    CzList args;
    
    CzVar varMapTypeID (args.CreateItem(VarID_int, "MapTypeID"));
    varMapTypeID.SetValue(VarID_int, & MapTypeID);

    CzVar retVar(localGetActiveFormat.Execute((ZLIST)args.GetZVAR()));
    
    ZFORMAT retValue;
    retVar.GetValue(VarID_format, &retValue);
    return retValue;

}

ZLIST classes_climate_GetTypeList (ZVAR hClimate)
{
    static CzFunc localGetTypeList;
    
    if (localGetTypeList.GetZVAR() == NULL)
        localGetTypeList.GetFunc("classes.climate.GetTypeList");

    CzList args;
    
    CzVar varhClimate (args.CreateItem(VarID_Climate, "hClimate"));
    varhClimate.SetValue(VarID_Climate, & hClimate);

    CzVar retVar(localGetTypeList.Execute((ZLIST)args.GetZVAR()));
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}

const char * classes_climate_GetName (ZVAR hClimate)
{
    static CzFunc localGetName;
    
    if (localGetName.GetZVAR() == NULL)
        localGetName.GetFunc("classes.climate.GetName");

    CzList args;
    
    CzVar varhClimate (args.CreateItem(VarID_Climate, "hClimate"));
    varhClimate.SetValue(VarID_Climate, & hClimate);

    CzVar retVar(localGetName.Execute((ZLIST)args.GetZVAR()));
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}

bool threadman_RunTiles (ZFUNC hTileFn, ZLIST TileList)
{
    static CzFunc localRunTiles;
    
    if (localRunTiles.GetZVAR() == NULL)
        localRunTiles.GetFunc("threadman.RunTiles");

    CzList args;
    
    CzVar varTileList (args.CreateItem(VarID_varlist, "TileList"));
    varTileList.SetValue(VarID_varlist, & TileList);

    CzVar retVar(localRunTiles.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

ZLIST zeofunc_GetFuncList ()
{
    static CzFunc localGetFuncList;
    
    if (localGetFuncList.GetZVAR() == NULL)
        localGetFuncList.GetFunc("zeofunc.GetFuncList");

    CzVar retVar(localGetFuncList.Execute());
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}
const char * application_GetTempDir ()
{
    static CzFunc localGetTempDir;
    
    if (localGetTempDir.GetZVAR() == NULL)
        localGetTempDir.GetFunc("application.GetTempDir");

    CzVar retVar(localGetTempDir.Execute());
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}
int application_GetUID ()
{
    static CzFunc localGetUID;
    
    if (localGetUID.GetZVAR() == NULL)
        localGetUID.GetFunc("application.GetUID");

    CzVar retVar(localGetUID.Execute());
    
    int retValue;
    retVar.GetValue(VarID_int, &retValue);
    return retValue;

}
bool project_IsInit ()
{
    static CzFunc localIsInit;
    
    if (localIsInit.GetZVAR() == NULL)
        localIsInit.GetFunc("project.IsInit");

    CzVar retVar(localIsInit.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
bool project_InitProject ()
{
    static CzFunc localInitProject;
    
    if (localInitProject.GetZVAR() == NULL)
        localInitProject.GetFunc("project.InitProject");

    CzVar retVar(localInitProject.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
bool project_FreeProject ()
{
    static CzFunc localFreeProject;
    
    if (localFreeProject.GetZVAR() == NULL)
        localFreeProject.GetFunc("project.FreeProject");

    CzVar retVar(localFreeProject.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
const char * project_GetProjectPath ()
{
    static CzFunc localGetProjectPath;
    
    if (localGetProjectPath.GetZVAR() == NULL)
        localGetProjectPath.GetFunc("project.GetProjectPath");

    CzVar retVar(localGetProjectPath.Execute());
    
    const char * retValue;
    retVar.GetValue(VarID_string, &retValue);
    return retValue;

}
LPVOID project_GetMap (const char * MapName)
{
    static CzFunc localGetMap;
    
    if (localGetMap.GetZVAR() == NULL)
        localGetMap.GetFunc("project.GetMap");

    CzList args;
    
    CzVar varMapName (args.CreateItem(VarID_string, "MapName"));
    varMapName.SetValue(VarID_string, & MapName);

    CzVar retVar(localGetMap.Execute((ZLIST)args.GetZVAR()));
    
    LPVOID retValue;
    retVar.GetValue(VarID_void, &retValue);
    return retValue;

}

ZLIST project_GetSettingsList ()
{
    static CzFunc localGetSettingsList;
    
    if (localGetSettingsList.GetZVAR() == NULL)
        localGetSettingsList.GetFunc("project.GetSettingsList");

    CzVar retVar(localGetSettingsList.Execute());
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}
ZLIST project_GetHeightfieldRange ()
{
    static CzFunc localGetHeightfieldRange;
    
    if (localGetHeightfieldRange.GetZVAR() == NULL)
        localGetHeightfieldRange.GetFunc("project.GetHeightfieldRange");

    CzVar retVar(localGetHeightfieldRange.Execute());
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}
void file_export_atlasEx (ZLIST MapList, const char * FileName, ZLIST Options)
{
    static CzFunc localatlasEx;
    
    if (localatlasEx.GetZVAR() == NULL)
        localatlasEx.GetFunc("file.export.atlasEx");

    CzList args;
    
    CzVar varOptions (args.CreateItem(VarID_varlist, "Options"));
    varOptions.SetValue(VarID_varlist, & Options);

    CzVar retVar(localatlasEx.Execute((ZLIST)args.GetZVAR()));
    return;
}

bool file_export_area (ZMAP hMap, const char * FileName, ZFORMAT hFormat, int x1, int x2, int y1, int y2)
{
    static CzFunc localarea;
    
    if (localarea.GetZVAR() == NULL)
        localarea.GetFunc("file.export.area");

    CzList args;
    
    CzVar vary2 (args.CreateItem(VarID_int, "y2"));
    vary2.SetValue(VarID_int, & y2);

    CzVar retVar(localarea.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

ZLIST climate_GetClimateList ()
{
    static CzFunc localGetClimateList;
    
    if (localGetClimateList.GetZVAR() == NULL)
        localGetClimateList.GetFunc("climate.GetClimateList");

    CzVar retVar(localGetClimateList.Execute());
    
    ZLIST retValue;
    retVar.GetValue(VarID_varlist, &retValue);
    return retValue;

}
void Sapphire_ExtRenderHF ()
{
    static CzFunc localExtRenderHF;
    
    if (localExtRenderHF.GetZVAR() == NULL)
        localExtRenderHF.GetFunc("Sapphire.ExtRenderHF");

    CzVar retVar(localExtRenderHF.Execute());
    return;
}
void Sapphire_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("Sapphire.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
void CopyPaste_ExtAbout ()
{
    static CzFunc localExtAbout;
    
    if (localExtAbout.GetZVAR() == NULL)
        localExtAbout.GetFunc("CopyPaste.ExtAbout");

    CzVar retVar(localExtAbout.Execute());
    return;
}
void CopyPaste_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("CopyPaste.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
void CopyPaste_ExtToggleWnd ()
{
    static CzFunc localExtToggleWnd;
    
    if (localExtToggleWnd.GetZVAR() == NULL)
        localExtToggleWnd.GetFunc("CopyPaste.ExtToggleWnd");

    CzVar retVar(localExtToggleWnd.Execute());
    return;
}
bool edit_copy ()
{
    static CzFunc localcopy;
    
    if (localcopy.GetZVAR() == NULL)
        localcopy.GetFunc("edit.copy");

    CzVar retVar(localcopy.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
bool edit_paste ()
{
    static CzFunc localpaste;
    
    if (localpaste.GetZVAR() == NULL)
        localpaste.GetFunc("edit.paste");

    CzVar retVar(localpaste.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
void atExportArea_ExtAbout ()
{
    static CzFunc localExtAbout;
    
    if (localExtAbout.GetZVAR() == NULL)
        localExtAbout.GetFunc("atExportArea.ExtAbout");

    CzVar retVar(localExtAbout.Execute());
    return;
}
bool atExportArea_ExtExportAreaUI ()
{
    static CzFunc localExtExportAreaUI;
    
    if (localExtExportAreaUI.GetZVAR() == NULL)
        localExtExportAreaUI.GetFunc("atExportArea.ExtExportAreaUI");

    CzVar retVar(localExtExportAreaUI.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
bool atExportArea_ExtExportAreaUIEx ()
{
    static CzFunc localExtExportAreaUIEx;
    
    if (localExtExportAreaUIEx.GetZVAR() == NULL)
        localExtExportAreaUIEx.GetFunc("atExportArea.ExtExportAreaUIEx");

    CzVar retVar(localExtExportAreaUIEx.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
void atFilterAM_ExtAbout ()
{
    static CzFunc localExtAbout;
    
    if (localExtAbout.GetZVAR() == NULL)
        localExtAbout.GetFunc("atFilterAM.ExtAbout");

    CzVar retVar(localExtAbout.Execute());
    return;
}
void atFilterAM_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("atFilterAM.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
void atFilterAM_ExtFilterAM ()
{
    static CzFunc localExtFilterAM;
    
    if (localExtFilterAM.GetZVAR() == NULL)
        localExtFilterAM.GetFunc("atFilterAM.ExtFilterAM");

    CzVar retVar(localExtFilterAM.Execute());
    return;
}
void atFilterAM_ExtAlphaExpress_UI ()
{
    static CzFunc localExtAlphaExpress_UI;
    
    if (localExtAlphaExpress_UI.GetZVAR() == NULL)
        localExtAlphaExpress_UI.GetFunc("atFilterAM.ExtAlphaExpress.UI");

    CzVar retVar(localExtAlphaExpress_UI.Execute());
    return;
}
bool atFilterAM_ExtEditFilterList ()
{
    static CzFunc localExtEditFilterList;
    
    if (localExtEditFilterList.GetZVAR() == NULL)
        localExtEditFilterList.GetFunc("atFilterAM.ExtEditFilterList");

    CzVar retVar(localExtEditFilterList.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
void atGrowTilesByOne_ExtAbout ()
{
    static CzFunc localExtAbout;
    
    if (localExtAbout.GetZVAR() == NULL)
        localExtAbout.GetFunc("atGrowTilesByOne.ExtAbout");

    CzVar retVar(localExtAbout.Execute());
    return;
}
void atGrowTilesByOne_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("atGrowTilesByOne.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
bool atGrowTilesByOne_ExtGrowTilesByOne (ZMAP hMap, const char * FileNameStr, ZFORMAT hFormat)
{
    static CzFunc localExtGrowTilesByOne;
    
    if (localExtGrowTilesByOne.GetZVAR() == NULL)
        localExtGrowTilesByOne.GetFunc("atGrowTilesByOne.ExtGrowTilesByOne");

    CzList args;
    
    CzVar varhFormat (args.CreateItem(VarID_format, "hFormat"));
    varhFormat.SetValue(VarID_format, & hFormat);

    CzVar retVar(localExtGrowTilesByOne.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

bool atGrowTilesByOne_ExtGrowMapByOne (ZMAP hMap, const char * FileNameStr, ZFORMAT hFormat)
{
    static CzFunc localExtGrowMapByOne;
    
    if (localExtGrowMapByOne.GetZVAR() == NULL)
        localExtGrowMapByOne.GetFunc("atGrowTilesByOne.ExtGrowMapByOne");

    CzList args;
    
    CzVar varhFormat (args.CreateItem(VarID_format, "hFormat"));
    varhFormat.SetValue(VarID_format, & hFormat);

    CzVar retVar(localExtGrowMapByOne.Execute((ZLIST)args.GetZVAR()));
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}

bool atGrowTilesByOne_ExtGrowMapByOneUI ()
{
    static CzFunc localExtGrowMapByOneUI;
    
    if (localExtGrowMapByOneUI.GetZVAR() == NULL)
        localExtGrowMapByOneUI.GetFunc("atGrowTilesByOne.ExtGrowMapByOneUI");

    CzVar retVar(localExtGrowMapByOneUI.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
bool atGrowTilesByOne_ExtGrowTilesByOneUI ()
{
    static CzFunc localExtGrowTilesByOneUI;
    
    if (localExtGrowTilesByOneUI.GetZVAR() == NULL)
        localExtGrowTilesByOneUI.GetFunc("atGrowTilesByOne.ExtGrowTilesByOneUI");

    CzVar retVar(localExtGrowTilesByOneUI.Execute());
    
    bool retValue;
    retVar.GetValue(VarID_bool, &retValue);
    return retValue;

}
void atFuncBrowser_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("atFuncBrowser.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
void atFuncBrowser_ExtShowFuncBrowser ()
{
    static CzFunc localExtShowFuncBrowser;
    
    if (localExtShowFuncBrowser.GetZVAR() == NULL)
        localExtShowFuncBrowser.GetFunc("atFuncBrowser.ExtShowFuncBrowser");

    CzVar retVar(localExtShowFuncBrowser.Execute());
    return;
}
void atFuncBrowser_ExtHideFuncBrowser ()
{
    static CzFunc localExtHideFuncBrowser;
    
    if (localExtHideFuncBrowser.GetZVAR() == NULL)
        localExtHideFuncBrowser.GetFunc("atFuncBrowser.ExtHideFuncBrowser");

    CzVar retVar(localExtHideFuncBrowser.Execute());
    return;
}
void atFuncBrowser_ExtToggleFuncBrowser ()
{
    static CzFunc localExtToggleFuncBrowser;
    
    if (localExtToggleFuncBrowser.GetZVAR() == NULL)
        localExtToggleFuncBrowser.GetFunc("atFuncBrowser.ExtToggleFuncBrowser");

    CzVar retVar(localExtToggleFuncBrowser.Execute());
    return;
}
void cdPython_ExtAbout ()
{
    static CzFunc localExtAbout;
    
    if (localExtAbout.GetZVAR() == NULL)
        localExtAbout.GetFunc("cdPython.ExtAbout");

    CzVar retVar(localExtAbout.Execute());
    return;
}
void cdPython_LoadScriptUI ()
{
    static CzFunc localLoadScriptUI;
    
    if (localLoadScriptUI.GetZVAR() == NULL)
        localLoadScriptUI.GetFunc("cdPython.LoadScriptUI");

    CzVar retVar(localLoadScriptUI.Execute());
    return;
}
void cdPython_ExtWikiPage ()
{
    static CzFunc localExtWikiPage;
    
    if (localExtWikiPage.GetZVAR() == NULL)
        localExtWikiPage.GetFunc("cdPython.ExtWikiPage");

    CzVar retVar(localExtWikiPage.Execute());
    return;
}
void cdPython_ExtZeoPage ()
{
    static CzFunc localExtZeoPage;
    
    if (localExtZeoPage.GetZVAR() == NULL)
        localExtZeoPage.GetFunc("cdPython.ExtZeoPage");

    CzVar retVar(localExtZeoPage.Execute());
    return;
}
void cdPython_LoadScript (const char * FileName)
{
    static CzFunc localLoadScript;
    
    if (localLoadScript.GetZVAR() == NULL)
        localLoadScript.GetFunc("cdPython.LoadScript");

    CzList args;
    
    CzVar varFileName (args.CreateItem(VarID_string, "FileName"));
    varFileName.SetValue(VarID_string, & FileName);

    CzVar retVar(localLoadScript.Execute((ZLIST)args.GetZVAR()));
    return;
}

void cdPython_RunScript (const char * ScriptStr)
{
    static CzFunc localRunScript;
    
    if (localRunScript.GetZVAR() == NULL)
        localRunScript.GetFunc("cdPython.RunScript");

    CzList args;
    
    CzVar varScriptStr (args.CreateItem(VarID_string, "ScriptStr"));
    varScriptStr.SetValue(VarID_string, & ScriptStr);

    CzVar retVar(localRunScript.Execute((ZLIST)args.GetZVAR()));
    return;
}

/* EOF */

